# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/krunner': '@latest-kf6'
    'frameworks/kactivities': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'
    'frameworks/kfilemetadata': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
    'plasma/plasma-workspace': '@same'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
